FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y openjdk-11-jre-headless && \
    apt-get clean && \
    echo "------ JAVA INSTALLED ------" && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/* && \
    echo "------ WGET INSTALLED ------" && \
    cd && \
    mkdir kafka && \
    cd kafka && \
    pwd && \
    wget https://dlcdn.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz && \
    echo "------ KAFKA INSTALLED ------" && \
    tar -xzf kafka_2.13-2.8.1.tgz && \
    cd kafka_2.13-2.8.1 && \
    echo "------ STARTING ZOOKEEPER ------"
CMD /root/kafka/kafka_2.13-2.8.1/bin/zookeeper-server-start.sh /root/kafka/kafka_2.13-2.8.1/config/zookeeper.properties
