apiVersion: v1
kind: Pod
metadata:
  name: backend-demo
  labels:
    app: backend-demo
spec:
  containers:
    - name: backend-demo
      image: backend-demo
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-demo
  ports:
    - port: 1234
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
