apiVersion: apps/v1
kind: Deployment
metadata:
  name: bosted
  labels:
    app: bosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bosted
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: bosted
        tier: backend
        track: stable
    spec:
      restartPolicy: Always
      containers:
        - name: bosted
          image: bosted
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bosted
spec:
  selector:
    app: bosted
    tier: backend
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30069