apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo
spec:
  selector:
    matchLabels:
      app: frontend-demo
  template:
    metadata:
      labels:
        app: frontend-demo
        tier: frontend
    spec:
      containers:
        - name: frontend-demo
          image: frontend-demo
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
