apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
  #   kompose.version: 1.21.0 (992df58d8)
  # creationTimestamp: null
  labels:
    io.kompose.service: kafkaa
  name: kafkaa
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
    # nodePort: 30073
  selector:
    io.kompose.service: kafkaa
  # type: LoadBalancer
  type: ClusterIP
# status:
#   loadBalancer: {}