FROM ubuntu:latest
RUN cd && \
    cd kafka && \
    cd kafka_2.13-2.8.1 && \
    echo "------ STARTING KAFKA SERVER ------"
CMD /root/kafka/kafka_2.13-2.8.1/bin/kafka-server-start.sh /root/kafka/kafka_2.13-2.8.1/config/server.properties
